version: '3'
services:
  db:
    image: postgres:15
    container_name: tool-db
    ports:
      - 55432:5432
    volumes:
      - tool_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: tool

  reference_db:
    image: postgres:15
    container_name: reference-db
    ports:
      - 65434:5432
    volumes:
      - reference_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: tool
volumes:
  tool_pgdata:
  reference_pgdata:
